# Generated by Django 3.1 on 2020-08-11 23:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Levantamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=None, max_length=100)),
                ('data_nascimento', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Levantamento_dados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variavel', models.CharField(default=None, max_length=45)),
                ('valor', models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('levantamento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='receptor.levantamento')),
            ],
        ),
        migrations.AddField(
            model_name='levantamento',
            name='participante',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='receptor.participante'),
        ),
    ]
