# Generated by Django 3.1 on 2020-08-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levantamento_dados',
            name='valor',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=10),
        ),
    ]
